### ISSUE TITLE
small change to 'bp_smp_get_icon_url_from_site_name' filter

### ISSUE THREAD

**Issue by locomo** [boonebgorges/bp-social-media-profiles#18]
it would make it much easier to customize the icons if the 'bp_smp_get_icon_url_from_site_name' filter passes $site_name

`return apply_filters( 'bp_smp_get_icon_url_from_site_name', BP_SMP_PLUGIN_URL . 'images/icons/' . $site_name . '.png', $site_name );
`
this would then allow something like this:
`add_filter( 'bp_smp_get_icon_url_from_site_name', 'my_custom_social_media_icons', 10, 2 );
function my_custom_social_media_icons( $icon_url, $site_name = '' ) {

	if ( 'twitter' == $site_name ) {
		$icon_url = "blar";
	}

	return $icon_url;

}`

**Comment by boonebgorges** [comment]
Definitely. This was surely an oversight when the filter was orignially written.

**Comment by locomo** [comment]
awesome, thanks
